package application.model.dtos.mobile.request;
// Generated 2015-11-23 23:39:49 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Rodzic generated by hbm2java
 */
public class RodzicMDTORequest implements java.io.Serializable {

    private Integer rodzicId;
    private Date dataUtworzenia;
    private String imie;
    private String haslo;
    private boolean status;
    private String email;
    private String numerTelefonu;

    public void setImie(String imie) {
        this.imie = imie;
    }

    public String getImie() {

        return imie;
    }

    public void setRodzicId(Integer rodzicId) {
        this.rodzicId = rodzicId;
    }

    public void setDataUtworzenia(Date dataUtworzenia) {
        this.dataUtworzenia = dataUtworzenia;
    }

    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setNumerTelefonu(String numerTelefonu) {
        this.numerTelefonu = numerTelefonu;
    }

    public Integer getRodzicId() {

        return rodzicId;
    }

    public Date getDataUtworzenia() {
        return dataUtworzenia;
    }

    public String getHaslo() {
        return haslo;
    }

    public boolean isStatus() {
        return status;
    }

    public String getEmail() {
        return email;
    }

    public String getNumerTelefonu() {
        return numerTelefonu;
    }

    public RodzicMDTORequest() {

    }

    public RodzicMDTORequest(Date dataUtworzenia , String imie, String haslo, boolean status, String email, String numerTelefonu) {
        this.dataUtworzenia = dataUtworzenia;
        this.imie = imie;
        this.haslo = haslo;
        this.status = status;
        this.email = email;
        this.numerTelefonu = numerTelefonu;
    }

}
