package application.model;
// Generated 2015-11-30 11:42:17 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kolejka generated by hbm2java
 */
@Entity
@Table(name = "kolejka", catalog = "praca_schema")
public class Kolejka implements java.io.Serializable {

	private Integer kolejkaId;
	private Dziecko dziecko;
	private Rodzic rodzic;
	private TypZadanie typZadanie;
	private int priorytet;
	private boolean status;
	private byte[] dane;
	private Date data;

	public Kolejka() {
	}

	public Kolejka(int priorytet, boolean status, Date data) {
		this.priorytet = priorytet;
		this.status = status;
		this.data = data;
	}

	public Kolejka(Dziecko dziecko, Rodzic rodzic, TypZadanie typZadanie, int priorytet, boolean status, byte[] dane,
			Date data) {
		this.dziecko = dziecko;
		this.rodzic = rodzic;
		this.typZadanie = typZadanie;
		this.priorytet = priorytet;
		this.status = status;
		this.dane = dane;
		this.data = data;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "kolejka_id", unique = true, nullable = false)
	public Integer getKolejkaId() {
		return this.kolejkaId;
	}

	public void setKolejkaId(Integer kolejkaId) {
		this.kolejkaId = kolejkaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_dzieckodziecko_id")
	public Dziecko getDziecko() {
		return this.dziecko;
	}

	public void setDziecko(Dziecko dziecko) {
		this.dziecko = dziecko;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_rodzicrodzic_id")
	public Rodzic getRodzic() {
		return this.rodzic;
	}

	public void setRodzic(Rodzic rodzic) {
		this.rodzic = rodzic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_typ_zadanie_zadanie_id")
	public TypZadanie getTypZadanie() {
		return this.typZadanie;
	}

	public void setTypZadanie(TypZadanie typZadanie) {
		this.typZadanie = typZadanie;
	}

	@Column(name = "priorytet", nullable = false)
	public int getPriorytet() {
		return this.priorytet;
	}

	public void setPriorytet(int priorytet) {
		this.priorytet = priorytet;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "dane")
	public byte[] getDane() {
		return this.dane;
	}

	public void setDane(byte[] dane) {
		this.dane = dane;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data", nullable = false, length = 19)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
