package application.model;
// Generated 2015-11-27 15:23:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kolejka generated by hbm2java
 */
@Entity
@Table(name = "kolejka", catalog = "praca_schema")
public class Kolejka implements java.io.Serializable {

	private Integer kolejkaId;
	private RodzicDziecko rodzicDziecko;
	private TypZadanie typZadanie;
	private int priorytet;
	private boolean status;
	private byte[] dane;
	private Date data;

	public Kolejka() {
	}

	public Kolejka(int priorytet, boolean status, byte[] dane, Date data) {
		this.priorytet = priorytet;
		this.status = status;
		this.dane = dane;
		this.data = data;
	}

	public Kolejka(RodzicDziecko rodzicDziecko, TypZadanie typZadanie, int priorytet, boolean status, byte[] dane,
			Date data) {
		this.rodzicDziecko = rodzicDziecko;
		this.typZadanie = typZadanie;
		this.priorytet = priorytet;
		this.status = status;
		this.dane = dane;
		this.data = data;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "kolejka_id", unique = true, nullable = false)
	public Integer getKolejkaId() {
		return this.kolejkaId;
	}

	public void setKolejkaId(Integer kolejkaId) {
		this.kolejkaId = kolejkaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "rodzic_dzieckorodzicrodzic_id", referencedColumnName = "rodzicrodzic_id"),
			@JoinColumn(name = "rodzic_dzieckodzieckodziecko_id", referencedColumnName = "dzieckodziecko_id") })
	public RodzicDziecko getRodzicDziecko() {
		return this.rodzicDziecko;
	}

	public void setRodzicDziecko(RodzicDziecko rodzicDziecko) {
		this.rodzicDziecko = rodzicDziecko;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_typ_zadanie_zadanie_id")
	public TypZadanie getTypZadanie() {
		return this.typZadanie;
	}

	public void setTypZadanie(TypZadanie typZadanie) {
		this.typZadanie = typZadanie;
	}

	@Column(name = "priorytet", nullable = false)
	public int getPriorytet() {
		return this.priorytet;
	}

	public void setPriorytet(int priorytet) {
		this.priorytet = priorytet;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "dane", nullable = false)
	public byte[] getDane() {
		return this.dane;
	}

	public void setDane(byte[] dane) {
		this.dane = dane;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data", nullable = false, length = 19)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
