package application.model;
// Generated 2015-11-30 22:04:58 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Parent generated by hbm2java
 */
@Entity
@Table(name = "parent", catalog = "praca_schema", uniqueConstraints = @UniqueConstraint(columnNames = "email") )
public class Parent implements java.io.Serializable {

	private Integer parentId;
	private String name;
	private String password;
	private Date creationDate;
	private boolean status;
	private String email;
	private String phoneNumber;
	private Set<Child> childs = new HashSet<Child>(0);
	private Set<Queue> queues = new HashSet<Queue>(0);

	public Parent() {
	}

	public Parent(String name, String password, Date creationDate, boolean status, String email, String phoneNumber) {
		this.name = name;
		this.password = password;
		this.creationDate = creationDate;
		this.status = status;
		this.email = email;
		this.phoneNumber = phoneNumber;
	}

	public Parent(String name, String password, Date creationDate, boolean status, String email, String phoneNumber,
			Set<Child> childs, Set<Queue> queues) {
		this.name = name;
		this.password = password;
		this.creationDate = creationDate;
		this.status = status;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.childs = childs;
		this.queues = queues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "parent_id", unique = true, nullable = false)
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_number", nullable = false, length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "parent_child", catalog = "praca_schema", joinColumns = {
			@JoinColumn(name = "parentparent_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "childchild_id", nullable = false, updatable = false) })
	public Set<Child> getChilds() {
		return this.childs;
	}

	public void setChilds(Set<Child> childs) {
		this.childs = childs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parent")
	public Set<Queue> getQueues() {
		return this.queues;
	}

	public void setQueues(Set<Queue> queues) {
		this.queues = queues;
	}

}
