package application.model;
// Generated 2015-11-23 23:39:49 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pozycja generated by hbm2java
 */
@Entity
@Table(name = "pozycja", catalog = "praca_schema")
public class Pozycja implements java.io.Serializable {

	private Integer pozycjaId;
	private Dziecko dziecko;
	private double dlugoscGeograficzna;
	private double szerokoscGeograficzna;
	private Date czas;

	public Pozycja() {
	}

	public Pozycja(Dziecko dziecko, double dlugoscGeograficzna, double szerokoscGeograficzna, Date czas) {
		this.dziecko = dziecko;
		this.dlugoscGeograficzna = dlugoscGeograficzna;
		this.szerokoscGeograficzna = szerokoscGeograficzna;
		this.czas = czas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pozycja_id", unique = true, nullable = false)
	public Integer getPozycjaId() {
		return this.pozycjaId;
	}

	public void setPozycjaId(Integer pozycjaId) {
		this.pozycjaId = pozycjaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_dziecko_dziecko_id", nullable = false)
	public Dziecko getDziecko() {
		return this.dziecko;
	}

	public void setDziecko(Dziecko dziecko) {
		this.dziecko = dziecko;
	}

	@Column(name = "dlugosc_geograficzna", nullable = false, precision = 22, scale = 0)
	public double getDlugoscGeograficzna() {
		return this.dlugoscGeograficzna;
	}

	public void setDlugoscGeograficzna(double dlugoscGeograficzna) {
		this.dlugoscGeograficzna = dlugoscGeograficzna;
	}

	@Column(name = "szerokosc_geograficzna", nullable = false, precision = 22, scale = 0)
	public double getSzerokoscGeograficzna() {
		return this.szerokoscGeograficzna;
	}

	public void setSzerokoscGeograficzna(double szerokoscGeograficzna) {
		this.szerokoscGeograficzna = szerokoscGeograficzna;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "czas", nullable = false, length = 19)
	public Date getCzas() {
		return this.czas;
	}

	public void setCzas(Date czas) {
		this.czas = czas;
	}

}
