package application.model;
// Generated 2015-11-30 22:04:58 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Queue generated by hbm2java
 */
@Entity
@Table(name = "queue", catalog = "praca_schema")
public class Queue implements java.io.Serializable {

	private Integer queueId;
	private Child child;
	private Parent parent;
	private int priority;
	private boolean status;
	private byte[] dane;
	private Date creationDate;

	public Queue() {
	}

	public Queue(Child child, Parent parent, int priority, boolean status, Date creationDate) {
		this.child = child;
		this.parent = parent;
		this.priority = priority;
		this.status = status;
		this.creationDate = creationDate;
	}

	public Queue(Child child, Parent parent, int priority, boolean status, byte[] dane, Date creationDate) {
		this.child = child;
		this.parent = parent;
		this.priority = priority;
		this.status = status;
		this.dane = dane;
		this.creationDate = creationDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "queue_id", unique = true, nullable = false)
	public Integer getQueueId() {
		return this.queueId;
	}

	public void setQueueId(Integer queueId) {
		this.queueId = queueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_child_id", nullable = false)
	public Child getChild() {
		return this.child;
	}

	public void setChild(Child child) {
		this.child = child;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_parent_id", nullable = false)
	public Parent getParent() {
		return this.parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "dane")
	public byte[] getDane() {
		return this.dane;
	}

	public void setDane(byte[] dane) {
		this.dane = dane;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
