package application.model;
// Generated 2015-11-27 15:23:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RodzicDzieckoId generated by hbm2java
 */
@Embeddable
public class RodzicDzieckoId implements java.io.Serializable {

	private int rodzicrodzicId;
	private int dzieckodzieckoId;

	public RodzicDzieckoId() {
	}

	public RodzicDzieckoId(int rodzicrodzicId, int dzieckodzieckoId) {
		this.rodzicrodzicId = rodzicrodzicId;
		this.dzieckodzieckoId = dzieckodzieckoId;
	}

	@Column(name = "rodzicrodzic_id", nullable = false)
	public int getRodzicrodzicId() {
		return this.rodzicrodzicId;
	}

	public void setRodzicrodzicId(int rodzicrodzicId) {
		this.rodzicrodzicId = rodzicrodzicId;
	}

	@Column(name = "dzieckodziecko_id", nullable = false)
	public int getDzieckodzieckoId() {
		return this.dzieckodzieckoId;
	}

	public void setDzieckodzieckoId(int dzieckodzieckoId) {
		this.dzieckodzieckoId = dzieckodzieckoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RodzicDzieckoId))
			return false;
		RodzicDzieckoId castOther = (RodzicDzieckoId) other;

		return (this.getRodzicrodzicId() == castOther.getRodzicrodzicId())
				&& (this.getDzieckodzieckoId() == castOther.getDzieckodzieckoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRodzicrodzicId();
		result = 37 * result + this.getDzieckodzieckoId();
		return result;
	}

}
