package application.model;
// Generated 2015-11-23 23:39:49 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RodzicDziecko generated by hbm2java
 */
@Entity
@Table(name = "rodzic_dziecko", catalog = "praca_schema")
public class RodzicDziecko implements java.io.Serializable {

	private Integer rodzicDzieckoId;
	private Rodzic rodzic;
	private Dziecko dziecko;
	private Set<Kolejka> kolejkas = new HashSet<Kolejka>(0);

	public RodzicDziecko() {
	}

	public RodzicDziecko(Rodzic rodzic, Dziecko dziecko) {
		this.rodzic = rodzic;
		this.dziecko = dziecko;
	}

	public RodzicDziecko(Rodzic rodzic, Dziecko dziecko, Set<Kolejka> kolejkas) {
		this.rodzic = rodzic;
		this.dziecko = dziecko;
		this.kolejkas = kolejkas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rodzic_dziecko_id", unique = true, nullable = false)
	public Integer getRodzicDzieckoId() {
		return this.rodzicDzieckoId;
	}

	public void setRodzicDzieckoId(Integer rodzicDzieckoId) {
		this.rodzicDzieckoId = rodzicDzieckoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_rodzic_rodzic_id", nullable = false)
	public Rodzic getRodzic() {
		return this.rodzic;
	}

	public void setRodzic(Rodzic rodzic) {
		this.rodzic = rodzic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_dziecko_dziecko_id", nullable = false)
	public Dziecko getDziecko() {
		return this.dziecko;
	}

	public void setDziecko(Dziecko dziecko) {
		this.dziecko = dziecko;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rodzicDziecko")
	public Set<Kolejka> getKolejkas() {
		return this.kolejkas;
	}

	public void setKolejkas(Set<Kolejka> kolejkas) {
		this.kolejkas = kolejkas;
	}

}
