package application.model;
// Generated 2015-11-30 11:42:17 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypZadanie generated by hbm2java
 */
@Entity
@Table(name = "typ_zadanie", catalog = "praca_schema")
public class TypZadanie implements java.io.Serializable {

	private Integer zadanieId;
	private String nazwa;
	private Set<Kolejka> kolejkas = new HashSet<Kolejka>(0);

	public TypZadanie() {
	}

	public TypZadanie(String nazwa) {
		this.nazwa = nazwa;
	}

	public TypZadanie(String nazwa, Set<Kolejka> kolejkas) {
		this.nazwa = nazwa;
		this.kolejkas = kolejkas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "zadanie_id", unique = true, nullable = false)
	public Integer getZadanieId() {
		return this.zadanieId;
	}

	public void setZadanieId(Integer zadanieId) {
		this.zadanieId = zadanieId;
	}

	@Column(name = "nazwa", nullable = false)
	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typZadanie")
	public Set<Kolejka> getKolejkas() {
		return this.kolejkas;
	}

	public void setKolejkas(Set<Kolejka> kolejkas) {
		this.kolejkas = kolejkas;
	}

}
